module.exports = {
	rules: {
		"array-bracket-spacing": [ 2, "always", { arraysInArrays: false, objectsInArrays: false, singleValue: false }],
		"block-spacing": 2,
		"brace-style": [ 2, "1tbs" ],
		camelcase: 2,
		"comma-dangle": [ 2, "always-multiline" ],
		"comma-spacing": [ 2, { after: true, before: false }],
		"comma-style": [ 2, "last" ],
		"computed-property-spacing": [ 2, "always" ],
		"consistent-this": 0,
		"eol-last": 2,
		"func-call-spacing": [ 2, "never" ],
		"func-name-matching": 2,
		"func-names": 2,
		"func-style": [ 2, "declaration", { allowArrowFunctions: true }],
		"id-blacklist": 0,
		"id-length": 0,
		"id-match": [ 2, "^(__)?(([A-Z]|[a-z]|[0-9]+)|([A-Z_]))*$" ], // camelCase, PascalCase, __filename, CONST_VALUE
		indent: [
			2,
			"tab",
			{
				FunctionDeclaration: { body: 1 },
				MemberExpression: 1,
				SwitchCase: 1,
			},
		],
		"jsx-quotes": [ 2, "prefer-double" ],
		"key-spacing": [ 2, { afterColon: true, beforeColon: false, mode: "minimum" }],
		"keyword-spacing": [
			2,
			{
				after: false,
				before: true,
				overrides: {
					const: { after: true },
					else: { after: true },
					from: { after: true },
					import: { after: true },
					let: { after: true },
					return: { after: true },
				},
			},
		],
		"line-comment-position": 0,
		"linebreak-style": 0,
		"lines-around-comment": [
			2,
			{
				allowArrayStart: true,
				allowBlockStart: true,
				allowObjectStart: true,
				beforeBlockComment: true,
				beforeLineComment: true,
			},
		],
		"lines-around-directive": 0,
		"max-depth": 0,
		"max-len": 0,
		"max-lines": 0,
		"max-nested-callbacks": 0,
		"max-params": 0,
		"max-statements": 0,
		"max-statements-per-line": 0,
		"multiline-ternary": 0,
		"new-cap": 2,
		"new-parens": 2,
		"newline-after-var": 2,
		"newline-before-return": 2,
		"newline-per-chained-call": 0,
		"no-array-constructor": 2,
		"no-bitwise": 0,
		"no-continue": 0,
		"no-inline-comments": 0,
		"no-lonely-if": 2,
		"no-mixed-operators": 2,
		"no-mixed-spaces-and-tabs": [ 2, "smart-tabs" ],
		"no-multiple-empty-lines": [ 2, { max: 1, maxEOF: 1 }],
		"no-negated-condition": 0,
		"no-nested-ternary": 2,
		"no-new-object": 2,
		"no-plusplus": 0,
		"no-restricted-syntax": 0,
		"no-tabs": 0,
		"no-ternary": 0,
		"no-trailing-spaces": 2,
		"no-underscore-dangle": 0,
		"no-unneeded-ternary": 2,
		"no-whitespace-before-property": 2,
		"object-curly-newline": 0,
		"object-curly-spacing": [ 2, "always" ],
		"object-property-newline": [ 2, { allowMultiplePropertiesPerLine: true }],
		"one-var": [ 2, "never" ],
		"one-var-declaration-per-line": [ 2, "initializations" ],
		"operator-assignment": [ 2, "always" ],
		"operator-linebreak": [ 2, "after" ],
		"padded-blocks": [ 2, "never" ],
		"quote-props": [ 2, "as-needed" ],
		quotes: [ 2, "double", { allowTemplateLiterals: true }],
		"require-jsdoc": 0,
		semi: [ 2, "never" ],
		"semi-spacing": 0,
		"sort-keys": 2,
		"sort-vars": 2,
		"space-before-blocks": 2,
		"space-before-function-paren": [ 2, "never" ],
		"space-in-parens": [ 2, "always", { exceptions: [ "{}", "[]", "empty" ] }],
		"space-infix-ops": 2,
		"space-unary-ops": [ 2, { nonwords: false, words: true }],
		"spaced-comment": [ 2, "always" ],
		"unicode-bom": 0,
		"wrap-regex": 0,
	},
}
